name: H6060 Experiment 2 - UrlLib3

on:
  workflow_dispatch:
    inputs:
      sast-codeql-enabled:
        description: Enable CodeQL scan (SAST)
        type: boolean
        required: false
        default: true

      sast-horusec-enabled:
        description: Enable Horusec scan (SAST)
        type: boolean
        required: false
        default: true

      sast-semgrep-enabled:
        description: Enable Semgrep scan (SAST)
        type: boolean
        required: false
        default: true

      sast-snyk-code-enabled:
        description: Enable Snyk Code scan (SAST)
        type: boolean
        required: false
        default: true

      sast-sonarqube-enabled:
        description: Enable SonarQube scan (SAST)
        type: boolean
        required: false
        default: true

      sca-eclipse-steady-enabled:
        description: Enable Eclipse Steady scan (SCA)
        type: boolean
        required: false
        default: true

      sca-grype-enabled:
        description: Enable Grype scan (SCA)
        type: boolean
        required: false
        default: true

      sca-owasp-dependency-check-enabled:
        description: Enable OWASP Dependency Check scan (SCA)
        type: boolean
        required: false
        default: true

      sca-snyk-enabled:
        description: Enable Snyk scan (SCA)
        type: boolean
        required: false
        default: true

      reporting-enabled:
        description: Enable reporting jobs
        type: boolean
        required: false
        default: true

defaults:
  run:
    shell: bash

permissions: write-all

jobs:
  build-application:
    name: Build Application
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python 3.8
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build

      - name: Build UrlLib3 Application - ${{ matrix.os }}
        uses: seansmith2600/H6060-Experiment-Resources/.github/actions/python/python-build@main
        with:
          build-command: python -m build
          build-directory: "dist"
          artifact-name: python-build-${{ matrix.os }}

  create-dependency-tree:
    name: Create Dependency Tree
    needs: build-application
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python 3.8
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Dependency Tree - ${{ matrix.os }}
        uses: seansmith2600/H6060-Experiment-Resources/.github/actions/python/python-dependency-tree@main
        with:
          artifact-name: dependency-tree-${{ matrix.os }}

  create-cyclonedx-sbom:
    name: Create CycloneDX SBOM
    needs: build-application
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          name: python-build-${{ matrix.os }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: ""
          commit: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Install Python 3.8
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create CycloneDX SBOM - ${{ matrix.os }}
        uses: seansmith2600/H6060-Experiment-Resources/.github/actions/python/python-cyclonedx-sbom@main
        with:
          artifact-name: cyclonedx-sbom-python-${{ matrix.os }}
